$script = <<SCRIPT

echo Installation depedencies...
sudo apt-get install -y unzip

echo Fetching Serf...
cd /tmp/
wget https://releases.hashicorp.com/serf/0.7.0/serf_0.7.0_linux_amd64.zip -O serf.zip

echo Installation Serf...
unzip serf.zip
sudo chmod +x serf
sudo mv serf /usr/bin/serf

echo Installation Dokuwiki...
cd /tmp
wget https://download.dokuwiki.org/src/docuwiki-stable.tgz
tar -xvf dokuwiki-stable.tgz

echo Deplacement de Dokuwiki...
sudo rm /var/www/html/index.html
sudo cp -r dokuwiki-2018-04-22b/* /var/html/
sudo chown -R vagrant:www-data /var/www/html

SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "generic/debian10"

    config.vm.provision "shell", inline: $script

    config.vm.define "n1" do |n1|
        n1.vm.network "private_network", ip: "172.20.20.10"
    end

    config.vm.define "n2" do |n2|
        n2.vm.network "private_network", ip: "172.20.20.11"
    end
end